# Usa la imagen oficial de Node.js
FROM node:18

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos del proyecto
COPY package.json package-lock.json ./
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto definido en tu backend
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["node", "app.js"]
